version: '3.9'

services:
  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j:/data
    environment:
      - NEO4J_AUTH=neo4j/5sS&v%^x5hxeglnq
  cdn:
    image: quay.io/minio/minio
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - minio:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=password
    command: ["server", "/data", "--console-address", ":9001"]

networks:
  factoryplanner:
    external: true

volumes:
  neo4j:
  minio:
