version: '3.9'

services:
  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j:/data
    env_file:
      - env/.env.neo4j
    networks:
      - factoryplanner
  cdn:
    image: quay.io/minio/minio
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - minio:/data
    env_file:
      - env/.env.minio
    command: ["server", "/data", "--console-address", ":9001"]
    networks:
      - factoryplanner

networks:
  factoryplanner:
    external: true

volumes:
  neo4j:
  minio:
